version: "3"

services:
  #
  # MESSAGES API
  #
  messages-redis:
    image: redis
    ports:
      - 6379:6379

  #
  # MESSAGES IOT API
  #
  messages-iot-api:
    container_name: messages-iot-api
    build: .
    # image: microapis/messages-iot-api:0.0.1
    ports:
      - 5060:5060
    environment:
      - PORT=5060
      - REDIS_HOST=messages-redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=1
      - PROVIDERS=nats,mqtt
      - PROVIDER_NATS_API_KEY=123
      - PROVIDER_MQTT_API_KEY=456
    depends_on:
      - messages-redis
    links:
      - messages-redis

  #
  # NATS SERVICE
  #
  nats:
    container_name: nats
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
