version: "3"

services:
  #
  # REDIS
  #
  events-redis:
    image: redis
    ports:
      - 6379:6379

  #
  # EVENTS API
  #
  events-api:
    container_name: events-api
    build: .
    # image: microapis/events-api:0.0.1
    ports:
      - 5060:5060
    environment:
      - PORT=5060
      - REDIS_HOST=events-redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=2
      # - PROVIDERS=nats,mqtt
      - PROVIDERS=nats
      - PROVIDER_NATS_API_KEY=123
      - PROVIDER_NATS_HOST=nats
      - PROVIDER_NATS_PORT=4222
      # - PROVIDER_MQTT_API_KEY=456
    depends_on:
      - events-redis
    links:
      - events-redis

  #
  # NATS SERVICE
  #
  nats:
    container_name: nats
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
