apiVersion: v1
kind: Service
metadata:
  name: events-api
  labels:
    app: events-api
    service: events-api
spec:
  ports:
    - port: 5060
      name: grpc
  selector:
    app: events-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
  labels:
    app: events-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-api
  template:
    metadata:
      labels:
        app: events-api
    spec:
      serviceAccountName: events-api
      containers:
        - name: events-api
          image: microapis/events-api:0.1.0
          ports:
            - containerPort: 5060
          env:
            - name: PORT
              value: "5060"
            - name: REDIS_HOST
              value: events-redis
            - name: REDIS_PORT
              value: 6379
            - name: REDIS_DATABASE
              value: 2
            - name: PROVIDERS
              value: nats,mqtt
            - name: PROVIDER_NATS_API_KEY
              value: <PROVIDER_NATS_API_KEY>
            - name: PROVIDER_MQTT_API_KEY
              value: <PROVIDER_MQTT_API_KEY>
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 1024Mi
